<?php
\_::$Router->On("public|asset/.*\.(js|css|flv|ico|pdf|avi|mov|ppt|doc|mp3|wmv|wav|gif|jpg|jpeg|png|swf|webm|webp)")
    ->Default(fn()=>deliverFile(normalizePath(\_::$Address->Request)));
\_::$Router->On("contents")->Default("contents");
\_::$Router->On("content")->Default("content");
\_::$Router->On("posts")->Default("posts");
\_::$Router->On("post")->Default("post");
\_::$Router->On("newses")->Default("newses");
\_::$Router->On("news")->Default("news");
\_::$Router->On("forums")->Default("forums");
\_::$Router->On("forum")->Default("forum");
\_::$Router->On("(categor(ies|y))|(cats?)")->Default("category");
\_::$Router->On("tags?")->Default("tag");
\_::$Router->On("query")->Default("query");
\_::$Router->On("search")->Default("search");
\_::$Router->On("sign")->Default("sign");
\_::$Router->On("user")->Default("user");
\_::$Router->On("group")->Default("group");
\_::$Router->On("contact/.+")->Default("contact");
\_::$Router->On()->Default(\_::$Router->DefaultRouteName);