<?php
\_::$Back->Router->On("public|asset/.*\.(js|css|flv|ico|pdf|avi|mov|ppt|doc|mp3|wmv|wav|gif|jpg|jpeg|png|swf|webm|webp)")
    ->Default(fn()=>responseFile(normalizePath(\_::$Request)));
\_::$Back->Router->On("contents")->Default("contents");
\_::$Back->Router->On("content")->Default("content");
\_::$Back->Router->On("posts")->Default("posts");
\_::$Back->Router->On("post")->Default("post");
\_::$Back->Router->On("newses")->Default("newses");
\_::$Back->Router->On("news")->Default("news");
\_::$Back->Router->On("forums")->Default("forums");
\_::$Back->Router->On("forum")->Default("forum");
\_::$Back->Router->On("(categor(ies|y))|(cats?)")->Default("category");
\_::$Back->Router->On("tags?")->Default("tag");
\_::$Back->Router->On("query")->Default("query");
\_::$Back->Router->On("search")->Default("search");
\_::$Back->Router->On("sign")->Default("sign");
\_::$Back->Router->On("user")->Default("user");
\_::$Back->Router->On("group")->Default("group");
\_::$Back->Router->On()->Default(\_::$Config->DefaultRouteName);
?>