<?php namespace MiMFa\Component;
use MiMFa\Library\Html;
class GeneralStyle{
	public static function Variables($rootSelector = ":root") { return "
		$rootSelector{
			--dir: ".(\_::$Back->Translate->Direction??\_::$Back->DefaultDirection).";
			--lang: ".(\_::$Back->Translate->Language??\_::$Back->DefaultLanguage).";
			--color-black: " . \_::$Front->Color(0) . ";
			--color-red: " . \_::$Front->Color(1) . ";
			--color-green: " . \_::$Front->Color(2) . ";
			--color-blue: " . \_::$Front->Color(3) . ";
			--color-yellow: " . \_::$Front->Color(4) . ";
			--color-cyan: " . \_::$Front->Color(5) . ";
			--color-magenta: " . \_::$Front->Color(6) . ";
			--color-white: " . \_::$Front->Color(7) . ";
			--fore-color: " . \_::$Front->ForeColor(0) . ";
			--fore-color-input: " . \_::$Front->ForeColor(1) . ";
			--fore-color-output: " . \_::$Front->ForeColor(2) . ";
			--fore-color-special: " . \_::$Front->ForeColor(3) . ";
			--fore-color-special-input: " . \_::$Front->ForeColor(4) . ";
			--fore-color-special-output: " . \_::$Front->ForeColor(5) . ";
			--back-color: " . \_::$Front->BackColor(0) . ";
			--back-color-input: " . \_::$Front->BackColor(1) . ";
			--back-color-output: " . \_::$Front->BackColor(2) . ";
			--back-color-special: " . \_::$Front->BackColor(3) . ";
			--back-color-special-input: " . \_::$Front->BackColor(4) . ";
			--back-color-special-output: " . \_::$Front->BackColor(5) . ";".(
			\_::$Front->SwitchMode?"
			--fore-color-0: " . \_::$Front->BackColor(0) . ";
			--fore-color-1: " . \_::$Front->BackColor(1) . ";
			--fore-color-2: " . \_::$Front->BackColor(2) . ";
			--fore-color-3: " . \_::$Front->BackColor(3) . ";
			--fore-color-4: " . \_::$Front->BackColor(4) . ";
			--fore-color-5: " . \_::$Front->BackColor(5) . ";
			--back-color-0: " . \_::$Front->ForeColor(0) . ";
			--back-color-1: " . \_::$Front->ForeColor(1) . ";
			--back-color-2: " . \_::$Front->ForeColor(2) . ";
			--back-color-3: " . \_::$Front->ForeColor(3) . ";
			--back-color-4: " . \_::$Front->ForeColor(4) . ";
			--back-color-5: " . \_::$Front->ForeColor(5) . ";":"
			--fore-color-0: " . \_::$Front->ForeColor(0) . ";
			--fore-color-1: " . \_::$Front->ForeColor(1) . ";
			--fore-color-2: " . \_::$Front->ForeColor(2) . ";
			--fore-color-3: " . \_::$Front->ForeColor(3) . ";
			--fore-color-4: " . \_::$Front->ForeColor(4) . ";
			--fore-color-5: " . \_::$Front->ForeColor(5) . ";
			--back-color-0: " . \_::$Front->BackColor(0) . ";
			--back-color-1: " . \_::$Front->BackColor(1) . ";
			--back-color-2: " . \_::$Front->BackColor(2) . ";
			--back-color-3: " . \_::$Front->BackColor(3) . ";
			--back-color-4: " . \_::$Front->BackColor(4) . ";
			--back-color-5: " . \_::$Front->BackColor(5) . ";"
			)."
			--font: " . \_::$Front->Font(0) . ";
			--font-input: " . \_::$Front->Font(1) . ";
			--font-output: " . \_::$Front->Font(2) . ";
			--font-special: " . \_::$Front->Font(3) . ";
			--font-special-input: " . \_::$Front->Font(4) . ";
			--font-special-output: " . \_::$Front->Font(5) . ";
			--size-0: " . \_::$Front->Size(0) . ";
			--size-1: " . \_::$Front->Size(1) . ";
			--size-2: " . \_::$Front->Size(2) . ";
			--size-3: " . \_::$Front->Size(3) . ";
			--size-4: " . \_::$Front->Size(4) . ";
			--size-5: " . \_::$Front->Size(5) . ";
			--size-min: " . first(\_::$Front->SizePalette) . ";
			--size-max: " . last(\_::$Front->SizePalette) . ";
			--shadow-0: " . \_::$Front->Shadow(0) . ";
			--shadow-1: " . \_::$Front->Shadow(1) . ";
			--shadow-2: " . \_::$Front->Shadow(2) . ";
			--shadow-3: " . \_::$Front->Shadow(3) . ";
			--shadow-4: " . \_::$Front->Shadow(4) . ";
			--shadow-5: " . \_::$Front->Shadow(5) . ";
			--shadow-min: " . first(\_::$Front->ShadowPalette) . ";
			--shadow-max: " . last(\_::$Front->ShadowPalette) . ";
			--border-0: " . \_::$Front->Border(0) . ";
			--border-1: " . \_::$Front->Border(1) . ";
			--border-2: " . \_::$Front->Border(2) . ";
			--border-3: " . \_::$Front->Border(3) . ";
			--border-4: " . \_::$Front->Border(4) . ";
			--border-5: " . \_::$Front->Border(5) . ";
			--border-min: " . first(\_::$Front->BorderPalette) . ";
			--border-max: " . last(\_::$Front->BorderPalette) . ";
			--radius-0: " . \_::$Front->Radius(0) . ";
			--radius-1: " . \_::$Front->Radius(1) . ";
			--radius-2: " . \_::$Front->Radius(2) . ";
			--radius-3: " . \_::$Front->Radius(3) . ";
			--radius-4: " . \_::$Front->Radius(4) . ";
			--radius-5: " . \_::$Front->Radius(5) . ";
			--radius-min: " . first(\_::$Front->RadiusPalette) . ";
			--radius-max: " . last(\_::$Front->RadiusPalette) . ";
			--transition-0: " . \_::$Front->Transition(0) . ";
			--transition-1: " . \_::$Front->Transition(1) . ";
			--transition-2: " . \_::$Front->Transition(2) . ";
			--transition-3: " . \_::$Front->Transition(3) . ";
			--transition-4: " . \_::$Front->Transition(4) . ";
			--transition-5: " . \_::$Front->Transition(5) . ";
			--transition-min: " . first(\_::$Front->TransitionPalette) . ";
			--transition-max: " . last(\_::$Front->TransitionPalette) . ";
			--overlay-0: \"" . \_::$Front->Overlay(0) . "\";
			--overlay-1: \"" . \_::$Front->Overlay(1) . "\";
			--overlay-2: \"" . \_::$Front->Overlay(2) . "\";
			--overlay-3: \"" . \_::$Front->Overlay(3) . "\";
			--overlay-4: \"" . \_::$Front->Overlay(4) . "\";
			--overlay-5: \"" . \_::$Front->Overlay(5) . "\";
			--overlay-min: " . first(\_::$Front->OverlayPalette) . ";
			--overlay-max: " . last(\_::$Front->OverlayPalette) . ";
			--pattern-0: \"" . \_::$Front->Pattern(0) . "\";
			--pattern-1: \"" . \_::$Front->Pattern(1) . "\";
			--pattern-2: \"" . \_::$Front->Pattern(2) . "\";
			--pattern-3: \"" . \_::$Front->Pattern(3) . "\";
			--pattern-4: \"" . \_::$Front->Pattern(4) . "\";
			--pattern-5: \"" . \_::$Front->Pattern(5) . "\";
			--pattern-min: " . first(\_::$Front->PatternPalette) . ";
			--pattern-max: " . last(\_::$Front->PatternPalette) . ";
			--overlay-url-0: URL(\"" . \_::$Front->Overlay(0) . "\");
			--overlay-url-1: URL(\"" . \_::$Front->Overlay(1) . "\");
			--overlay-url-2: URL(\"" . \_::$Front->Overlay(2) . "\");
			--overlay-url-3: URL(\"" . \_::$Front->Overlay(3) . "\");
			--overlay-url-4: URL(\"" . \_::$Front->Overlay(4) . "\");
			--overlay-url-5: URL(\"" . \_::$Front->Overlay(5) . "\");
			--overlay-url-min: URL(\"" . first(\_::$Front->OverlayPalette) . "\");
			--overlay-url-max: URL(\"" . last(\_::$Front->OverlayPalette) . "\");
			--pattern-url-0: URL(\"" . \_::$Front->Pattern(0) . "\");
			--pattern-url-1: URL(\"" . \_::$Front->Pattern(1) . "\");
			--pattern-url-2: URL(\"" . \_::$Front->Pattern(2) . "\");
			--pattern-url-3: URL(\"" . \_::$Front->Pattern(3) . "\");
			--pattern-url-4: URL(\"" . \_::$Front->Pattern(4) . "\");
			--pattern-url-5: URL(\"" . \_::$Front->Pattern(5) . "\");
			--pattern-url-min: URL(\"" . first(\_::$Front->PatternPalette) . "\");
			--pattern-url-max: URL(\"" . last(\_::$Front->PatternPalette) . "\");

			--owner: \"" . __(\_::$Info->Owner, true, false) . "\";
			--name: \"" . __(\_::$Info->Name, true, false) . "\";
			--slogan: \"" . __(\_::$Info->Slogan, true, false) . "\";

			--path: \"" . \_::$Info->Path . "\";
			--home-path: \"" . \_::$Info->HomePath . "\";
			--logo-path: \"" . asset(\_::$Info->LogoPath) . "\";
			--full-logo-path: \"" . asset(\_::$Info->FullLogoPath) . "\";
			--banner-path: \"" . asset(\_::$Info->BannerPath) . "\";
			--full-banner-path: \"" . asset(\_::$Info->FullBannerPath) . "\";
			--wait-symbol-path: \"" . asset(\_::$Info->WaitSymbolPath) . "\";
			--process-symbol-path: \"" . asset(\_::$Info->ProcessSymbolPath) . "\";
			--error-symbol-path: \"" . asset(\_::$Info->ErrorSymbolPath) . "\";

			--logo-path-url: URL(\"" . asset(\_::$Info->LogoPath) . "\");
			--full-logo-path-url: URL(\"" . asset(\_::$Info->FullLogoPath) . "\");
			--banner-path-url: URL(\"" . asset(\_::$Info->BannerPath) . "\");
			--full-banner-path-url: URL(\"" . asset(\_::$Info->FullBannerPath) . "\");
			--wait-symbol-path-url: URL(\"" . asset(\_::$Info->WaitSymbolPath) . "\");
			--process-symbol-path-url: URL(\"" . asset(\_::$Info->ProcessSymbolPath) . "\");
			--error-symbol-path-url: URL(\"" . asset(\_::$Info->ErrorSymbolPath) . "\");
		}";
	}
	public static function SwitchVariables($rootSelector = ":root") { return "
		$rootSelector{
			--fore-color: " . \_::$Front->BackColor(0) . ";
			--fore-color-input: " . \_::$Front->BackColor(1) . ";
			--fore-color-output: " . \_::$Front->BackColor(2) . ";
			--fore-color-special: " . \_::$Front->BackColor(3) . ";
			--fore-color-special-input: " . \_::$Front->BackColor(4) . ";
			--fore-color-special-output: " . \_::$Front->BackColor(5) . ";
			--back-color: " . \_::$Front->ForeColor(0) . ";
			--back-color-input: " . \_::$Front->ForeColor(1) . ";
			--back-color-output: " . \_::$Front->ForeColor(2) . ";
			--back-color-special: " . \_::$Front->ForeColor(3) . ";
			--back-color-special-input: " . \_::$Front->ForeColor(4) . ";
			--back-color-special-output: " . \_::$Front->ForeColor(5) . ";
		}";
	}
}
\_::$Front->Libraries[] = Html::Style(null, asset(\_::$Address->StyleDirectory,'reset.css', optimize: true));
\_::$Front->Libraries[] = Html::Style(GeneralStyle::Variables());
\_::$Front->Libraries[] = Html::Style(null, asset(\_::$Address->StyleDirectory,'general.css', optimize: true));
\_::$Front->Libraries[] = Html::Script(null, asset(\_::$Address->ScriptDirectory, 'general.js', optimize: true));